require("dotenv").config();
const fs=require("fs");
const BASE=process.env.FREEBROWSER_URL||"http://127.0.0.1:8765";
const QUEUE_FILE="./job-queue.json";
const SOCIAL=/^((www|m)\.)?(instagram|facebook|youtube|youtu|tiktok|twitter|x|linkedin)\.com$/i;
const ATS=/(^|\.)(myworkdayjobs\.com|greenhouse\.io|lever\.co|ashbyhq\.com|icims\.com|smartrecruiters\.com|workday\.com)$/i;
const CLOSED=[/no longer available/i,/no longer accepting applications/i,/applications? (?:are|is) (?:now )?closed/i,/job has been filled/i,/position has been filled/i,/job (?:posting )?has expired/i,/requisition (?:has )?closed/i];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function host(v){try{return new URL(v).hostname.toLowerCase()}catch{return""}}
function clean(v){try{const u=new URL(String(v));if(/^google\./i.test(u.hostname)){const t=u.searchParams.get("url")||u.searchParams.get("q");return t?decodeURIComponent(t):u.href}return u.href}catch{return""}}
function social(v){return SOCIAL.test(host(clean(v)))}
function official(v,company){const h=host(clean(v));if(!h||social(v))return false;const c=String(company||"").toLowerCase().replace(/[^a-z0-9]/g,"");const f=String(company||"").toLowerCase().split(/\s+/)[0].replace(/[^a-z0-9]/g,"");return ATS.test(h)||/(^|\.)careers?\.|(^|\.)jobs?\./i.test(h)||(c&&h.includes(c))||(f.length>2&&h.includes(f))}
async function api(path,method="GET",body){const r=await fetch(`${BASE}${path}`,{method,headers:body?{"content-type":"application/json"}:{},body:body?JSON.stringify(body):undefined});const t=await r.text();let d;try{d=JSON.parse(t)}catch{throw Error(`FreeBrowser returned non-JSON from ${path}`)}if(!r.ok||d.ok===false)throw Error(d.error||`FreeBrowser ${r.status}`);return d}
async function evalJS(s){const d=await api("/evaluate","POST",{script:s});try{return JSON.parse(d.result)}catch{return d.result}}
async function snap(){return evalJS(`(()=>({url:location.href,title:document.title,text:(document.body?.innerText||"").slice(0,30000),links:[...document.querySelectorAll("a")].map(a=>({text:(a.innerText||a.textContent||a.getAttribute("aria-label")||"").replace(/\\s+/g," ").trim(),href:a.href||""})).filter(x=>x.text&&x.href)}))()`)}
function score(x,j){if(social(x.href))return -10000;const t=`${x.text} ${x.href}`.toLowerCase();let s=0;if(t.includes(String(j.company).toLowerCase()))s+=30;if(official(x.href,j.company))s+=25;if(ATS.test(host(x.href)))s+=20;for(const w of String(j.title).toLowerCase().split(/[^a-z0-9]+/).filter(x=>x.length>3))if(t.includes(w))s+=2;return s}
async function search(j,q){await api("/navigate","POST",{url:`https://www.google.com/search?q=${encodeURIComponent(q)}`});await sleep(1800);const d=await snap();return d.links.map(x=>({...x,href:clean(x.href)})).filter(x=>/^https?:/i.test(x.href)&&!/^google\./i.test(host(x.href))&&!social(x.href)).map(x=>({x,s:score(x,j)})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s).map(x=>x.x)}
async function main(){const q=JSON.parse(fs.readFileSync(QUEUE_FILE,"utf8"));const i=q.findIndex(j=>j.status!=="verified"&&j.status!=="closed"&&j.application_status!=="applied");if(i<0){console.log("No unverified job is waiting.");return}const j=q[i];console.log("\n🤖 VERIFYING ONE JOB\n\nTitle:",j.title,"\nCompany:",j.company,"\nPosting URL:",j.posting_url||"not stored — discovery will run in FreeBrowser");const st=await api("/status");console.log(`🌐 FreeBrowser: ${st.browserAttached?"connected":"not attached"}`);if(!st.browserAttached)throw Error("FreeBrowser browser is not attached. Open FreeBrowser first.");let url=social(j.posting_url)?null:j.posting_url;if(!url){const r=await search(j,`"${j.title}" "${j.company}" ${j.location||""}`);url=r[0]?.href||null}if(!url||social(url)){q[i]={...j,status:"needs_review",verification_error:"No valid employer/ATS posting URL found"};fs.writeFileSync(QUEUE_FILE,JSON.stringify(q,null,2));console.log("⚠️ No valid employer/ATS posting URL found.");return}await api("/navigate","POST",{url});await sleep(2500);const d=await snap();const closed=CLOSED.some(r=>r.test(d.text));let app=null;if(!closed){const direct=d.links.map(x=>({...x,href:clean(x.href)})).filter(x=>!social(x.href)&&official(x.href,j.company));app=direct.find(x=>/apply|application|careers|job details|view job/i.test(x.text))?.href||direct[0]?.href||null}if(!app&&!closed){const r=await search(j,`"${j.title}" "${j.company}" ${j.location||""} official careers apply`);app=r.find(x=>official(x.href,j.company))?.href||null}q[i]={...j,posting_url:url,resolved_url:d.url,page_title:d.title,description:d.text,official_url:app||j.official_url||null,status:closed?"closed":(app||j.official_url?"verified":"needs_review"),verified_at:new Date().toISOString(),verification_error:closed?"Job posting is closed or no longer accepting applications":(app||j.official_url?undefined:"Official application URL not identified")};if(!q[i].verification_error)delete q[i].verification_error;fs.writeFileSync(QUEUE_FILE,JSON.stringify(q,null,2));console.log("\n🌐 FINAL URL:\n"+d.url+"\n\n📄 PAGE TITLE:\n"+d.title+"\n\n🔗 OFFICIAL APPLICATION:\n"+(app||j.official_url||"Not identified")+`\n\n${closed?"🚫 Job is closed.":app||j.official_url?"✅ Job verified.":"⚠️ Needs review."}\n💾 Saved verification to job-queue.json\n\n✅ Posting inspection complete.\nFreeBrowser sessions used: 0 cloud sessions`)}
main().catch(e=>{console.error("\n❌ ERROR:",e.message);process.exit(1)})
